### ISSUE TITLE
Installation error during "composer install"

### ISSUE THREAD

**Issue by ch40s** [madmis/wexnz-bot#1]
Error during the installation.
```
...
  - Installing symfony/yaml (dev-master cf16b19): Downloading (100%)
  - Installing symfony/dotenv (dev-master 34fd101): Downloading (100%)
Generating autoload files
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In FileLocator.php line 44:
!!
!!    The file "wexnz-bot/app/config/packages" does not exist.
!!
!!
!!
```

Execution fails too:

```
$php bin/console simple-bot:run shorting-bot-config.yaml

In FileLocator.php line 44:

  The file "wexnz-bot/app/config/packages" does not exist.

```

**Comment by ch40s** [comment]
If I create the directory "packages" and retry, I get the following error:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In ParameterBag.php line 100:
!!
!!    The service "uri_signer" has a dependency on a non-existent parameter "kern
!!    el.secret". Did you mean this: "kernel.charset"?
!!
!!
!!
```

**Comment by madmis** [comment]
@ch40s it was a bug. My fault. 
Just update the package to latest version and run `composer install` again. 
It should work after this.

Run bot:
```
 bin/console shorting-bot:run shorting-bot-config.yaml
```

**Comment by madmis** [comment]
@ch40s please tell me about your progress. 
Can i close this issue?

**Comment by ch40s** [comment]
Hi @madmis , thanks for your quick response. Installation worked but execution gives me the following error:
```
$php bin/console simple-bot:run shorting-bot-config.yaml
2017-12-01T14:26:49+00:00 [error] Error thrown while running command "'simple-bot:run' 'shorting-bot-config.yaml'". Message: "There are no commands defined in the "simple-bot" namespace."


  There are no commands defined in the "simple-bot" namespace.


```

**Comment by ch40s** [comment]
Never mind, I replaced "simple-bot:run" and "shorting-bot:run" and it's running now. I keep seeing the following error though:

```
Unhandled exception: Warning: file_put_contents(/var/www/var//[PUBLIC-API-KEY]-nonce.dat): failed to open stream: No such file or directory
```

**Comment by madmis** [comment]
@ch40s when bot started, it created file to store some info for exchange api.
Seems like bot don't have rights to vrite into this directory.
Try to change permissions to **/var/www/var**
Or create this file manually.

**Comment by ch40s** [comment]
Thanks, I created the directory /var/www/var (not under wexnz-bot/app/var) and fixed the permissions so I don't get the same error anymore. 

```
Unhandled exception: no trades
```

**Comment by madmis** [comment]
It's require time. I will look on it after weekend.

Seems like it can be related to the trading history. As a hack you can: make manual buy and then sell for a coin which you want trade with bot (for a small amount, its required only for trading history). This should resolve this problem.

I will let you know when fix this.

**Comment by ch40s** [comment]
You are right, it needs some history so a manual trade solves that problem.
